name: CI pipeline

on:
  push:
    branches: ["main", "dev", "test"]
  pull_request:
    branches: ["main", "dev", "test"]

env:
  NODE_VERSION: '24'
  PNPM_VERSION: '10'
  SITE_URL: ${{ vars.SITE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint project
        run: pnpm lint

      - name: Run tests
        run: pnpm test
